### ISSUE TITLE
Sample Config Failure

### ISSUE THREAD

**Issue by Nastras** [keybuk/homebridge-sun-position#1]
Hello, thank you for the nice plugin. I have just installed it and I noticed that in your example config an error exists.

Currently: "long" -115.8067
Right: "long": -115.8067

otherwise the plugin will not work .-)

**Comment by Nastras** [comment]
I still have a question for you how or where can I determine which value is the right one now to control my blinds?

**Comment by keybuk** [comment]
Thanks, I've fixed the example config.

To determine the right values, the easiest way is just to sit in the room, wait until the point at which the sun coming from the window is a problem, and open a HomeKit app that can show the characteristic values and note them down.

Or you could use an orienteering-style compass for the azimuth, stand in the room, look through the compass out of the window to the sides, the values you read are the angles at which the sun will be a problem for you (when the sun is at 180° of azimuth, it means it's exactly to your South).

For altitude you can use a sextant, same basic principle, look through the window and measure the angles of the top and bottoms of the window.

There are apps for both of these things if you don't have a physical one.
