### ISSUE TITLE
heartbeat drift potentially caused by homebridge-sun-position?

### ISSUE THREAD

**Issue by Lorccan** [keybuk/homebridge-sun-position#10]
I had an issue with another homebridge plugin that was warning of heartbeat drifts. I asked the developer about this and he said it was likely due to another plugin blocking the NodeJS main thread 'typically by doing synchronous I/O'

I've been through my installed plugins and disabled them in turn and, unfortunately, homebridge-sun-position is the one that, when disabled, suppresses the heartbeat drifts.

Obviously, I can't prove that this plugin is the source of the problem. Can you check please whether you are doing something that might block the NodeJS main thread?

**Comment by keybuk** [comment]
Unless you have a reproducible failure, with details, I cannot arbitrarily debug a problem with your system

**Comment by keybuk** [comment]
This plugin performs no significant work, aside from a little math. It certainly doesn't perform any long-term blocking operations
