### ISSUE TITLE
Disable logging?

### ISSUE THREAD

**Issue by chrismclay** [keybuk/homebridge-sun-position#11]
Thank you for the hard work on this plugin. 

Is there an option to disable logging of the positions? They are useful is setting things up, but now everything is working well, it would be good to disable them.

**Comment by keybuk** [comment]
Glad it's helpful.

My homebridge installation is generally pretty chatty, with most plugins logging frequently on state changes.

My personal stance on options is that every option permutation must be tested before release, which makes adding them logarithmic.

While it might seem like a trivial request, I've seen code in the last week alone that changed behavior based on the presence or not of a debug log call.

So I'd rather not make this code more complex (even in an apparently trivial way).

**Comment by chrismclay** [comment]
That makes sense. I hoped it might already be in the code. Thank you.
