### ISSUE TITLE
Sun position

### ISSUE THREAD

**Issue by bakman2** [keybuk/homebridge-sun-position#2]
As your plugin currently only produces the current lux, perhaps you could consider to include something like [suncalc](https://github.com/mourner/suncalc) to get the actual position and expose it for automation in stead of using an external app ?

*edit* I see you use suncalc my mistake, can you expose the position values ?

**Comment by keybuk** [comment]
The plugin does expose the position values - both azimuth and altitude

However the default Apple Home.app only displays certain characteristics, to see and use these, you would need to use an alternative HomeKit app such as the one suggested in the README.
