### ISSUE TITLE
Remove empty SerialNumber value (breaks homebridge 1.0.x)

### ISSUE THREAD

**Issue by bauer-andreas** [keybuk/homebridge-sun-position#4]
Talking about the following line
https://github.com/keybuk/homebridge-sun-position/blob/ed5f09876f3c5651c9247453ffbab077bac34ce3/index.js#L70

And empty string is a invalid value for the SerialNumber characteristic and will be replaced anyways by a default number.

**Comment by keybuk** [comment]
I haven't seen any problems, what issue is this causing for you?

**Comment by bauer-andreas** [comment]
This **was** causing issues for pretty much every user currently on 1.0.x (with 1.0.3-beta.5) mitigating the error. Previous to 1.0.0 it was checked, that such values where not published. Now they are ignored again. See https://github.com/homebridge/homebridge/issues/2518#issuecomment-620857440 and further/previous responses.

Just saying if this value is ignored anyways, might as well just remove it.

**Comment by keybuk** [comment]
Thanks for the link!

The plugin was pretty much just cargo-culted from looking at the code of other plugins, so I just left things unchanged if I didn't know what to put there

**Comment by bauer-andreas** [comment]
The issue was fixed in homebridge 1.0.3 (it seems like some other plugins did the same stuff). But at least we maybe can prevent something similar in the future 😅

**Comment by keybuk** [comment]
This should be fixed now
