### ISSUE TITLE
suncalc updates

### ISSUE THREAD

**Issue by newmans99** [keybuk/homebridge-sun-position#5]
I noticed that suncalc gets frequent updates but that homebridge-sun-position does not. Is there a way to check what version of suncalc I am running in my homebridge environment? Thanks.

Using Docker version, if it matters.

**Comment by keybuk** [comment]
suncalc hasn't been updated in over three years, the latest version is still 1.8.0 which is the minimum version homebridge-sun-position has been tested against

**Comment by newmans99** [comment]
Thanks. I must have gone down a wrong dependency route.
