### ISSUE TITLE
`minStep: 0.1` not respected

### ISSUE THREAD

**Issue by wimleers** [keybuk/homebridge-sun-position#9]
👋 I've been using this excellent plugin for over a year now, and it works well!

But along the way I've seen erratic behavior in HomeKit. And now I wonder if it's related to `minStep: 0.1` not being respected:
![546B75A6-966A-4C61-BCBE-641253F5EB02](https://user-images.githubusercontent.com/14240/201025038-bfcbcab7-52a9-4f2e-92d5-df880e1826bf.jpeg)

Even if this isn't causing problems, I think the code ought to set values that conform to the details specified in the characteristic, _and_ it'd make for simpler to read values 🤓

**Comment by keybuk** [comment]
Could you give a more detailed description of the problem that you've having?

The HAP specification implies that this is used for rounding values sent to the accessory, which as a read-only characteristic, this does not support.

> Minimum step value for the characteristic, which is only appropriate for characteristics that have a format of ”int” or ”float”. For example, if this were 0.15, the characteristic value can be incremented from the minimum value in multiples of 0.15. For “float”, the “Value” needs to be rounded on the accessory side to the closest allowed value per the ”Step Value” (e.g. a value of 10.150001 received on the accessory side with a ”Step Value” of 0.15 and a ”Minimum Value” of 10.0 needs to be interpreted as 10.15).
